USE [master]
GO

CREATE DATABASE [nlp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nlp', FILENAME = N'D:\rdsdbdata\DATA\nlp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'nlp_log', FILENAME = N'D:\rdsdbdata\DATA\nlp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nlp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nlp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nlp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nlp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nlp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nlp] SET ARITHABORT OFF 
GO

ALTER DATABASE [nlp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nlp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nlp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nlp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nlp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nlp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nlp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nlp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nlp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nlp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nlp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nlp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nlp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nlp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nlp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nlp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nlp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nlp] SET RECOVERY FULL 
GO

ALTER DATABASE [nlp] SET  MULTI_USER 
GO

ALTER DATABASE [nlp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nlp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nlp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nlp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [nlp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [nlp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [nlp] SET  READ_WRITE 
GO
